stages:
  - test

visual-regression:
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  stage: test
  image: node:16
  services:
    - docker:dind
  before_script:
    - curl -L http://get.docker.io | bash
    - apt update && apt install -y graphicsmagick
    - docker info
  script:
    - yarn
    - cd src && yarn run visual-regression || true
  artifacts:
    paths:
      - src/.loki
    expire_in: 1 week
  when: manual
