stages:
  - test

visual-regression:
  stage: test
  image: registry.gitlab.com/risserlabs/community/images/node:16.14.2
  before_script:
    - apt update && apt install -y graphicsmagick chromium make git-lfs
  script:
    - yarn
    - make -s src/vr-test || true
  artifacts:
    paths:
      - src/.loki
    expire_in: 1 week
  when: manual
