stages:
  - test

visual-regression:
  stage: test
  image: node:16
  before_script:
    - apt update && apt install -y graphicsmagick chromium
  script:
    - yarn
    - cd src && yarn run visual-regression || true
  artifacts:
    paths:
      - src/.loki
    expire_in: 1 week
  when: manual
